import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { SOAPNote } from '../types';
import fs from 'fs';
import path from 'path';

export class ExportService {
  /**
   * Generate PDF from SOAP note
   */
  async generatePDF(soapNote: SOAPNote, patientIdentifier?: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(20).text('Clinical Documentation', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });

        if (patientIdentifier) {
          doc.text(`Patient: ${patientIdentifier}`, { align: 'center' });
        }

        doc.moveDown(1.5);

        // SOAP sections
        this.addSection(doc, 'SUBJECTIVE', soapNote.subjective);
        this.addSection(doc, 'OBJECTIVE', soapNote.objective);
        this.addSection(doc, 'ASSESSMENT', soapNote.assessment);
        this.addSection(doc, 'PLAN', soapNote.plan);

        // Footer
        doc.moveDown(2);
        doc.fontSize(8)
          .fillColor('gray')
          .text(
            'This document was generated by Clinical Docs AI. Please review for accuracy.',
            { align: 'center' }
          );

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate DOCX from SOAP note
   */
  async generateDOCX(soapNote: SOAPNote, patientIdentifier?: string): Promise<Buffer> {
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              text: 'Clinical Documentation',
              heading: HeadingLevel.HEADING_1,
              spacing: { after: 200 },
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `Generated: ${new Date().toLocaleString()}`,
                  size: 20,
                }),
              ],
              spacing: { after: 100 },
            }),
            ...(patientIdentifier
              ? [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: `Patient: ${patientIdentifier}`,
                        size: 20,
                      }),
                    ],
                    spacing: { after: 300 },
                  }),
                ]
              : []),
            this.createSection('SUBJECTIVE', soapNote.subjective),
            this.createSection('OBJECTIVE', soapNote.objective),
            this.createSection('ASSESSMENT', soapNote.assessment),
            this.createSection('PLAN', soapNote.plan),
            new Paragraph({
              children: [
                new TextRun({
                  text: 'This document was generated by Clinical Docs AI. Please review for accuracy.',
                  size: 18,
                  italics: true,
                  color: '808080',
                }),
              ],
              spacing: { before: 400 },
            }),
          ],
        },
      ],
    });

    return await Packer.toBuffer(doc);
  }

  private addSection(doc: PDFKit.PDFDocument, title: string, content: string) {
    doc.fontSize(14).fillColor('black').text(title, { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('black').text(content);
    doc.moveDown(1);
  }

  private createSection(title: string, content: string): Paragraph {
    return new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 28,
        }),
        new TextRun({
          text: '\n\n' + content,
          size: 22,
        }),
      ],
      spacing: { after: 300 },
    });
  }
}

export default new ExportService();
